name: Auto Label PR

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        run: |
          echo "Setting up GitHub CLI"
          echo "gh version $(gh --version)"
          gh auth login --with-token $GITHUB_TOKEN

      - name: Set labels
        run: |
          TITLE=$(echo "${{ github.event.pull_request.title }}" | tr '[:upper:]' '[:lower:]')

          if [[ $TITLE == *'fix'* ]]; then
            echo "Applying 'fix' label"
            gh pr edit --add-label fix
          fi

          if [[ $TITLE == *'enhancement'* ]]; then
            echo "Applying 'enhancement' label"
            gh pr edit --add-label enhancement
          fi

          if [[ $TITLE == *'wip'* ]]; then
            echo "Applying 'WIP' label"
            gh pr edit --add-label WIP
          fi
