name: Add Revision Label

on:
  pull_request:
    types:
      - opened

jobs:
  add_revision_label:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Add Revision Label
        run: |
          gh pr edit ${{ github.event.number }} --add-label "REVISION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
