name: Pull Request Labeler

on:
  pull_request:
    types:
      - opened

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set labels
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const title = github.context.payload.pull_request?.title;
          const labelsToAdd = [];

          if (title && title.includes('bug')) {
            labelsToAdd.push('bug');
          }

          if (title && title.includes('feature')) {
            labelsToAdd.push('enhancement');
          }

          if (labelsToAdd.length > 0) {
            await github.issues.addLabels({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              issue_number: github.context.payload.pull_request.number,
              labels: labelsToAdd,
            });
          }
